# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c23554d2058d8c7159053c8534e1f55c5e2244ec20c8e26a39b121a2ffbd56ae110bf6641132f7aa0e89cebd420d9729c1a833611a644e18e46f97e9e3be68

test:
  secret_key_base: 960ccf795d0c10ae74feb91d962e5644f36931f3e44a0de5b553bba85978ad2bbf06b279d69a5234fd78aa99ee0aebd2f68263b6078f6a5eaddfa49421c3f0dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
